#!/usr/bin/env bash
set -euo pipefail

# Refreshes supabase/schema/current-schema.sql from a live database when possible.
# This script is intentionally conservative:
# - it only works when DATABASE_URL is provided
# - it requires pg_dump to be available locally
# - it does not edit migration history

OUT_FILE="supabase/schema/current-schema.sql"

if ! command -v pg_dump >/dev/null 2>&1; then
  echo "pg_dump is required to auto-refresh snapshot."
  echo "Install PostgreSQL client tools or refresh manually per docs/database/current-schema.md."
  exit 1
fi

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is not set."
  echo "Example: DATABASE_URL='postgresql://...' scripts/refresh-schema-snapshot.sh"
  exit 1
fi

TMP_FILE="${OUT_FILE}.tmp"

pg_dump \
  --schema-only \
  --no-owner \
  --no-privileges \
  --schema=public \
  "$DATABASE_URL" > "$TMP_FILE"

{
  echo "-- CURRENT SCHEMA SNAPSHOT (generated)"
  echo "-- Generated by scripts/refresh-schema-snapshot.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "-- Migration history remains in supabase/migrations/*"
  echo
  cat "$TMP_FILE"
} > "$OUT_FILE"

rm -f "$TMP_FILE"

echo "Updated $OUT_FILE"
